[package]
name = "logic-form"
version = "0.2.9"
license = "MIT"
description = "Rust library for representing Cube, Clause, CNF and DNF"
edition = "2021"
repository = "https://github.com/gipsyh/logic-form"
authors = ["Yuheng Su <gipsyh.icu@gmail.com>"]
keywords = ["logic", "cube", "cnf"]
rust-version = "1.85"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
no_bound_check = []

[dependencies]
giputils = { path = "../giputils", version = "0.2" }
ahash = "0.8.11"
