[package]
name = "logic-form"
version = "0.1.0"
license = "MIT"
description = "Rust library for representing Cube, Clause, CNF and DNF"
edition = "2021"
repository = "https://github.com/gipsyh/logic-form"
authors = ["Yuheng Su <gipsyh.icu@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
